{
  "exploitdb": [],
  "itw": [
    {
      "id": "CVE-2023-1436",
      "description": "An infinite recursion is triggered in Jettison when constructing a JSONArray from a Collection that contains a self-reference in one of its elements. This leads to a StackOverflowError exception being thrown.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2023-1436",
      "reportURL": "https://research.jfrog.com/vulnerabilities/jettison-json-array-dos-xray-427911/",
      "timeStamp": "2023-03-29T19:07:00Z"
    }
  ],
  "trickest": [
    {
      "id": "CVE-2023-1436",
      "url": "https://research.jfrog.com/vulnerabilities/jettison-json-array-dos-xray-427911/",
      "added_at": "1970-01-01T00:00:00Z"
    }
  ],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2023-1436",
      "url": "https://research.jfrog.com/vulnerabilities/jettison-json-array-dos-xray-427911/",
      "added_at": "2023-03-29T19:07:00Z",
      "score": 0,
      "template_for": ""
    }
  ]
}
