{
  "exploitdb": [],
  "itw": [],
  "trickest": [
    {
      "id": "CVE-2024-39705",
      "url": "https://github.com/nltk/nltk/issues/3266",
      "added_at": "2024-06-28T06:31:53Z"
    },
    {
      "id": "CVE-2024-39705",
      "url": "https://www.vicarius.io/vsociety/posts/rce-in-python-nltk-cve-2024-39705-39706",
      "added_at": "1970-01-01T00:00:00Z"
    }
  ],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2024-39705",
      "url": "https://github.com/nltk/nltk/issues/3266",
      "added_at": "2024-06-28T06:31:53Z",
      "score": 0.4,
      "template_for": ""
    },
    {
      "cve": "CVE-2024-39705",
      "url": "https://www.vicarius.io/vsociety/posts/rce-in-python-nltk-cve-2024-39705-39706",
      "added_at": "1970-01-01T00:00:00Z",
      "score": 0,
      "template_for": ""
    }
  ]
}
