{
  "exploitdb": [],
  "itw": [],
  "trickest": [
    {
      "id": "CVE-2024-33663",
      "url": "https://github.com/mpdavis/python-jose/issues/346",
      "added_at": "2024-09-03T22:23:48Z"
    },
    {
      "id": "CVE-2024-33663",
      "url": "https://www.vicarius.io/vsociety/posts/algorithm-confusion-in-python-jose-cve-2024-33663",
      "added_at": "1970-01-01T00:00:00Z"
    }
  ],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2024-33663",
      "url": "https://github.com/mpdavis/python-jose/issues/346",
      "added_at": "2024-09-03T22:23:48Z",
      "score": 0.4,
      "template_for": ""
    },
    {
      "cve": "CVE-2024-33663",
      "url": "https://www.vicarius.io/vsociety/posts/algorithm-confusion-in-python-jose-cve-2024-33663",
      "added_at": "1970-01-01T00:00:00Z",
      "score": 0,
      "template_for": ""
    }
  ]
}
