{
  "exploitdb": [],
  "itw": [
    {
      "id": "CVE-2018-10879",
      "description": "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause a use-after-free in ext4_xattr_set_entry function and a denial of service or unspecified other impact may occur by renaming a file in a crafted ext4 filesystem image.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2018-10879",
      "reportURL": "https://bugzilla.kernel.org/show_bug.cgi?id=200001",
      "timeStamp": "2019-10-09T23:33:00Z"
    }
  ],
  "trickest": [
    {
      "id": "CVE-2018-10879",
      "url": "https://bugzilla.kernel.org/show_bug.cgi?id=200001",
      "added_at": "1970-01-01T00:00:00Z"
    }
  ],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2018-10879",
      "url": "https://bugzilla.kernel.org/show_bug.cgi?id=200001",
      "added_at": "2019-10-09T23:33:00Z",
      "score": 0,
      "template_for": ""
    }
  ]
}
