{
  "exploitdb": [
    {
      "cve": "CVE-2018-7886",
      "id": "44470",
      "file": "exploits/windows/local/44470.py",
      "description": "CloudMe Sync 1.11.0 - Local Buffer Overflow",
      "author": "Prasenjit Kanti Paul",
      "application_url": "http://www.exploit-db.comCloudMe_1110.exe",
      "source_url": "",
      "screenshot": "",
      "verified": false,
      "codes": "CVE-2018-7886",
      "tags": "Local",
      "type": "local",
      "platform": "windows",
      "port": "",
      "aliases": "",
      "date_added": "2018-04-16T00:00:00Z",
      "date_updated": "2018-04-16T00:00:00Z",
      "date_published": "2018-04-16T00:00:00Z"
    }
  ],
  "itw": [
    {
      "id": "CVE-2018-7886",
      "description": "An issue was discovered in CloudMe 1.11.0. An unauthenticated local attacker that can connect to the \"CloudMe Sync\" client application listening on 127.0.0.1 port 8888 can send a malicious payload causing a buffer overflow condition. This will result in code execution, as demonstrated by a TCP reverse shell, or a crash. NOTE: this vulnerability exists because of an incomplete fix for CVE-2018-6892.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2018-7886",
      "reportURL": "https://0day4u.wordpress.com/2018/03/09/buffer-overflow-on-cloudme-sync-v1-11-0/",
      "timeStamp": "2019-03-04T15:50:00Z"
    },
    {
      "id": "CVE-2018-7886",
      "description": "An issue was discovered in CloudMe 1.11.0. An unauthenticated local attacker that can connect to the \"CloudMe Sync\" client application listening on 127.0.0.1 port 8888 can send a malicious payload causing a buffer overflow condition. This will result in code execution, as demonstrated by a TCP reverse shell, or a crash. NOTE: this vulnerability exists because of an incomplete fix for CVE-2018-6892.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2018-7886",
      "reportURL": "https://www.exploit-db.com/exploits/44470",
      "timeStamp": "2019-03-04T15:50:00Z"
    }
  ],
  "trickest": [
    {
      "id": "CVE-2018-7886",
      "url": "https://www.exploit-db.com/exploits/44470",
      "added_at": "2022-02-19T16:34:00Z"
    }
  ],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2018-7886",
      "url": "https://0day4u.wordpress.com/2018/03/09/buffer-overflow-on-cloudme-sync-v1-11-0/",
      "added_at": "2019-03-04T15:50:00Z",
      "score": 0,
      "template_for": ""
    },
    {
      "cve": "CVE-2018-7886",
      "url": "https://www.exploit-db.com/exploits/44470",
      "added_at": "2018-04-16T00:00:00Z",
      "score": 0.5,
      "template_for": ""
    }
  ]
}
