{
  "exploitdb": [],
  "itw": [
    {
      "id": "CVE-2018-16438",
      "description": "An issue was discovered in the HDF HDF5 1.8.20 library. There is an out of bounds read in H5L_extern_query at H5Lexternal.c.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2018-16438",
      "reportURL": "https://github.com/TeamSeri0us/pocs/tree/master/hdf5/h5stat",
      "timeStamp": "2018-10-26T15:36:00Z"
    }
  ],
  "trickest": [
    {
      "id": "CVE-2018-16438",
      "url": "https://github.com/TeamSeri0us/pocs/tree/master/hdf5/h5stat",
      "added_at": "1970-01-01T00:00:00Z"
    }
  ],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2018-16438",
      "url": "https://github.com/TeamSeri0us/pocs/tree/master/hdf5/h5stat",
      "added_at": "2018-10-26T15:36:00Z",
      "score": 0,
      "template_for": ""
    }
  ]
}
