{
  "exploitdb": [],
  "itw": [
    {
      "id": "CVE-2019-1010142",
      "description": "scapy 2.4.0 is affected by: Denial of Service. The impact is: infinite loop, resource consumption and program unresponsive. The component is: _RADIUSAttrPacketListField.getfield(self..). The attack vector is: over the network or in a pcap. both work.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2019-1010142",
      "reportURL": "https://www.imperva.com/blog/scapy-sploit-python-network-tool-is-vulnerable-to-denial-of-service-dos-attack-cve-pending/",
      "timeStamp": "2020-08-24T17:37:00Z"
    }
  ],
  "trickest": [],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2019-1010142",
      "url": "https://www.imperva.com/blog/scapy-sploit-python-network-tool-is-vulnerable-to-denial-of-service-dos-attack-cve-pending/",
      "added_at": "2020-08-24T17:37:00Z",
      "score": 0,
      "template_for": ""
    }
  ]
}
