{
  "exploitdb": [],
  "itw": [
    {
      "id": "CVE-2020-15701",
      "description": "An unhandled exception in check_ignored() in apport/report.py can be exploited by a local attacker to cause a denial of service. If the mtime attribute is a string value in apport-ignore.xml, it will trigger an unhandled exception, resulting in a crash. Fixed in 2.20.1-0ubuntu2.24, 2.20.9-0ubuntu7.16, 2.20.11-0ubuntu27.6.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2020-15701",
      "reportURL": "https://launchpad.net/bugs/1877023",
      "timeStamp": "2020-09-14T16:15:00Z"
    }
  ],
  "trickest": [
    {
      "id": "CVE-2020-15701",
      "url": "https://github.com/Live-Hack-CVE/CVE-2020-15701",
      "added_at": "2023-02-04T07:53:18Z"
    }
  ],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2020-15701",
      "url": "https://github.com/Live-Hack-CVE/CVE-2020-15701",
      "added_at": "2023-02-04T07:53:18Z",
      "score": 0,
      "template_for": ""
    },
    {
      "cve": "CVE-2020-15701",
      "url": "https://launchpad.net/bugs/1877023",
      "added_at": "2020-09-14T16:15:00Z",
      "score": 0,
      "template_for": ""
    }
  ]
}
