{
  "exploitdb": [],
  "itw": [
    {
      "id": "CVE-2022-33124",
      "description": "AIOHTTP 3.8.1 can report a \"ValueError: Invalid IPv6 URL\" outcome, which can lead to a Denial of Service (DoS). NOTE: multiple third parties dispute this issue because there is no example of a context in which denial of service would occur, and many common contexts have exception handing in the calling application",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2022-33124",
      "reportURL": "https://github.com/aio-libs/aiohttp/issues/6772",
      "timeStamp": "2022-07-01T13:16:00Z"
    }
  ],
  "trickest": [
    {
      "id": "CVE-2022-33124",
      "url": "https://github.com/aio-libs/aiohttp/issues/6772",
      "added_at": "2022-12-24T13:45:51Z"
    }
  ],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2022-33124",
      "url": "https://github.com/aio-libs/aiohttp/issues/6772",
      "added_at": "2022-07-01T13:16:00Z",
      "score": 0.4,
      "template_for": ""
    }
  ]
}
