{
  "exploitdb": [],
  "itw": [
    {
      "id": "CVE-2022-0924",
      "description": "Out-of-bounds Read error in tiffcp in libtiff 4.3.0 allows attackers to cause a denial-of-service via a crafted tiff file. For users that compile libtiff from sources, the fix is available with commit 408976c4.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2022-0924",
      "reportURL": "https://gitlab.com/libtiff/libtiff/-/issues/278",
      "timeStamp": "2022-03-18T20:15:00Z"
    }
  ],
  "trickest": [
    {
      "id": "CVE-2022-0924",
      "url": "https://gitlab.com/libtiff/libtiff/-/issues/278",
      "added_at": "2022-03-12T04:49:39Z"
    },
    {
      "id": "CVE-2022-0924",
      "url": "https://gitlab.com/libtiff/libtiff/-/merge_requests/311",
      "added_at": "2022-03-12T04:49:39Z"
    }
  ],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [
    {
      "cve": "CVE-2022-0924",
      "url": "https://www.cve.news/cve-2022-0924/",
      "added_at": "2023-01-16T00:00:00Z",
      "score": 1,
      "template_for": ""
    }
  ],
  "openpoc": [
    {
      "cve": "CVE-2022-0924",
      "url": "https://gitlab.com/libtiff/libtiff/-/issues/278",
      "added_at": "2022-03-12T04:49:39Z",
      "score": 0.4,
      "template_for": ""
    },
    {
      "cve": "CVE-2022-0924",
      "url": "https://gitlab.com/libtiff/libtiff/-/merge_requests/311",
      "added_at": "2022-03-12T04:49:39Z",
      "score": 0.4,
      "template_for": ""
    },
    {
      "cve": "CVE-2022-0924",
      "url": "https://www.cve.news/cve-2022-0924/",
      "added_at": "2023-01-16T00:00:00Z",
      "score": 1,
      "template_for": ""
    }
  ]
}
