{
  "exploitdb": [],
  "itw": [
    {
      "id": "CVE-2022-26280",
      "description": "Libarchive v3.6.0 was discovered to contain an out-of-bounds read via the component zipx_lzma_alone_init.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2022-26280",
      "reportURL": "https://github.com/libarchive/libarchive/issues/1672",
      "timeStamp": "2022-04-05T15:18:00Z"
    }
  ],
  "trickest": [],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [
    {
      "cve": "CVE-2022-26280",
      "url": "https://www.cve.news/cve-2022-26280/",
      "addedAt": "2023-01-16T12:45:34Z",
      "score": 1
    }
  ],
  "openpoc": [
    {
      "cve": "CVE-2022-26280",
      "url": "https://github.com/libarchive/libarchive/issues/1672",
      "added_at": "2022-04-05T15:18:00Z",
      "score": 0.4,
      "template_for": ""
    },
    {
      "cve": "CVE-2022-26280",
      "url": "https://www.cve.news/cve-2022-26280/",
      "added_at": "2023-01-16T12:45:34Z",
      "score": 1,
      "template_for": "nuclei"
    }
  ]
}
