{
  "exploitdb": [],
  "itw": [
    {
      "id": "CVE-2021-3502",
      "description": "A flaw was found in avahi 0.8-5. A reachable assertion is present in avahi_s_host_name_resolver_start function allowing a local attacker to crash the avahi service by requesting hostname resolutions through the avahi socket or dbus methods for invalid hostnames. The highest threat from this vulnerability is to the service availability.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2021-3502",
      "reportURL": "https://bugzilla.redhat.com/show_bug.cgi?id=1946914",
      "timeStamp": "2021-05-17T17:30:00Z"
    },
    {
      "id": "CVE-2021-3502",
      "description": "A flaw was found in avahi 0.8-5. A reachable assertion is present in avahi_s_host_name_resolver_start function allowing a local attacker to crash the avahi service by requesting hostname resolutions through the avahi socket or dbus methods for invalid hostnames. The highest threat from this vulnerability is to the service availability.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2021-3502",
      "reportURL": "https://github.com/lathiat/avahi/issues/338",
      "timeStamp": "2021-05-17T17:30:00Z"
    }
  ],
  "trickest": [],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2021-3502",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1946914",
      "added_at": "2021-05-17T17:30:00Z",
      "score": 0.4,
      "template_for": ""
    },
    {
      "cve": "CVE-2021-3502",
      "url": "https://github.com/lathiat/avahi/issues/338",
      "added_at": "2021-05-17T17:30:00Z",
      "score": 0.4,
      "template_for": ""
    }
  ]
}
