{
  "exploitdb": [],
  "itw": [
    {
      "id": "CVE-2021-4150",
      "description": "A use-after-free flaw was found in the add_partition in block/partitions/core.c in the Linux kernel. A local attacker with user privileges could cause a denial of service on the system. The issue results from the lack of code cleanup when device_add call fails when adding a partition to the disk.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2021-4150",
      "reportURL": "https://lkml.org/lkml/2021/10/18/485",
      "timeStamp": "2022-03-30T20:02:00Z"
    },
    {
      "id": "CVE-2021-4150",
      "description": "A use-after-free flaw was found in the add_partition in block/partitions/core.c in the Linux kernel. A local attacker with user privileges could cause a denial of service on the system. The issue results from the lack of code cleanup when device_add call fails when adding a partition to the disk.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2021-4150",
      "reportURL": "https://lkml.org/lkml/2021/9/6/781",
      "timeStamp": "2022-03-30T20:02:00Z"
    }
  ],
  "trickest": [],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2021-4150",
      "url": "https://lkml.org/lkml/2021/10/18/485",
      "added_at": "2022-03-30T20:02:00Z",
      "score": 0,
      "template_for": ""
    },
    {
      "cve": "CVE-2021-4150",
      "url": "https://lkml.org/lkml/2021/9/6/781",
      "added_at": "2022-03-30T20:02:00Z",
      "score": 0,
      "template_for": ""
    }
  ]
}
