{
  "exploitdb": [],
  "itw": [],
  "trickest": [
    {
      "id": "CVE-2013-1633",
      "url": "https://www.reddit.com/r/Python/comments/17rfh7/warning_dont_use_pip_in_an_untrusted_network_a/",
      "added_at": "1970-01-01T00:00:00Z"
    }
  ],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2013-1633",
      "url": "https://www.reddit.com/r/Python/comments/17rfh7/warning_dont_use_pip_in_an_untrusted_network_a/",
      "added_at": "1970-01-01T00:00:00Z",
      "score": 0,
      "template_for": ""
    }
  ]
}
